---
# 校验 MongoDB Exporter 是否安装
- name: '<{{ cmd | upper }}> | 校验 MongoDB Exporter 是否安装'
  stat:
    path: '{{ flag }}'
  register: ret

# 安装 MongoDB Exporter
- block: 
  - name: '<{{ cmd | upper }}> | 创建 MongoDB Exporter 相关目录'
    file:
      path: '{{ mongodb_exporter.dir }}'
      state: directory

  - name: '<{{ cmd | upper }}> | 安装 MongoDB Exporter'
    template: 
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
    loop:
    - src: docker-compose.yml.j2
      dest: '{{ mongodb_exporter.dir }}/docker-compose.yml'

  - name: '<{{ cmd | upper }}> | 启动 MongoDB Exporter 容器'
    shell: |
      . /etc/profile
      cd {{ mongodb_exporter.dir }}
      docker-compose down
      docker-compose up -d

#  - name: '<{{ cmd | upper }}> | 等待 MongoDB Exporter 服务启动'
#    wait_for:
#      port: '{{ mongodb_exporter.port }}'

  - name: '<{{ cmd | upper }}> | 创建 MongoDB Exporter 安装标记'
    shell: |
      set -ex
      mkdir -p ~/.flag
      touch {{ flag }}

  when:
  - cmd == "install"
  - not ret.stat.exists
  - ansible_architecture == "x86_64"

# 卸载 MongoDB Exporter
- block:
  - name: '<{{ cmd | upper }}> | 卸载 MongoDB Exporter'
    shell: |
      . /etc/profile
      cd {{ mongodb_exporter.dir }}
      docker-compose down

  - name: '<{{ cmd | upper }}> | 清除 MongoDB Exporter 相关文件'
    shell: |
      rm -rf {{ mongodb_exporter.dir }}
      rm -rf {{ flag }}

  when:
  - cmd == "remove"
  - ret.stat.exists
  - ansible_architecture == "x86_64"
